# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [47]:
import numpy as np

In [48]:
# создание матрицы 3х3

m1 = np.array([[i+j*3 for i in range(1, 4)] for j in range(3)])
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
# прибавление единичной матрицы

m2 = m1 + np.eye(3)
m2

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [50]:
# умножение на вектор

m3 = np.dot(m2, np.array([1, 2, 3]))
m3

array([15., 34., 53.])

In [52]:
# вычисление транспонированной матрицы

m4 = np.transpose(m2)
m4

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [54]:
# вычисление обратной матрицы

m5 = np.linalg.inv(m2)
m5

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

In [55]:
m2@m5

array([[ 1.00000000e+00, -3.33066907e-16,  6.66133815e-16],
       [-5.32907052e-15,  1.00000000e+00,  1.33226763e-15],
       [-1.77635684e-15, -1.11022302e-15,  1.00000000e+00]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [61]:
m = np.array([[2, 2], [1, 3]])

res = np.linalg.eig(m)

In [62]:
# собственные значения

res[0]

array([1., 4.])

In [63]:
# собственные вектора

res[1]

array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])

### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [ ]:
1 3 1
2 2 1
4 1 1

2 + 12 + 2 - 8 - 6 -1

In [67]:
np.linalg.det(np.array([[1, 3, 1], [2, 2, 1], [4, 1, 1]]))

1.0000000000000004